services:
  loki:
    image: grafana/loki:3.3.2
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - loki-data:/loki

  grafana:
    build:
      context: grafana
    depends_on:
      - loki
    volumes:
      - "grafana-data:/var/lib/grafana"
    environment:
      CONTEXT_PATH: ${CONTEXT_PATH}
    secrets:
      - grafana-password

volumes:
  loki-data:
  grafana-data:

secrets:
  grafana-password:
    file: .secrets/grafana-password.txt
