services:
  loki:
    image: grafana/loki:3.3.2
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - loki-data:/loki

  grafana:
    image: "grafana/grafana:11.4.0"
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/loki.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    volumes:
      - "grafana-data:/var/lib/grafana"

volumes:
  loki-data:
  grafana-data:
