include:
  - compose-postgres.yaml
  - compose-observability.yml

services:
  web-app:
    build: .
    depends_on:
      - postgres
      - loki
    hostname: grading-server
    ports:
      - "${PORT}:8080"
      - "127.0.0.1:6000:6000" # JMX main VM
      - "127.0.0.1:6001:6001" # JMX test runner VM
    environment:
      SERVER_SERVLET_CONTEXT_PATH: ${CONTEXT_PATH}
      JAVA_TOOL_OPTIONS: ${VM_ARGS}
      GRADING_SERVER_TEST_RUNNER_VM_ARGS: ${TEST_RUNNER_VM_ARGS}
      SPRING_CONFIG_IMPORT: configtree:/run/secrets/
    secrets:
      - source: postgres-password
        target: spring.datasource.password
