services:
  postgres:
    image: 'postgres:17.0'
    environment:
      - 'POSTGRES_USER=grading-server'
      - 'POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password'
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - '127.0.0.1:5432:5432'
    secrets:
      - postgres-password

  postgres-backup:
    build:
      context: postgres-backup
    depends_on:
      - postgres
    environment:
      - 'PGHOST=postgres'
      - 'PGUSER=grading-server'
      - 'PGPASSFILE=/run/secrets/postgres-password'
    volumes:
      - "${BACKUP_DIR}:/backup"
    secrets:
      - postgres-password

volumes:
  postgres-data:

secrets:
  postgres-password:
    file: .secrets/postgres-password.txt
