services:
  web-app:
    build: .
    depends_on:
      - postgres
      - loki
    hostname: grading-server
    ports:
      - "${PORT}:8080"
      - "127.0.0.1:6000:6000" # JMX main VM
      - "127.0.0.1:6001:6001" # JMX test runner VM
    environment:
      SERVER_SERVLET_CONTEXT_PATH: ${CONTEXT_PATH}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JAVA_TOOL_OPTIONS: ${VM_ARGS}
      GRADING_SERVER_TEST_RUNNER_VM_ARGS: ${TEST_RUNNER_VM_ARGS}

  postgres:
    extends:
      file: compose-postgres.yaml
      service: postgres

  postgres-backup:
    extends:
      file: compose-postgres.yaml
      service: postgres-backup

  loki:
    extends:
      file: compose-observability.yml
      service: loki

  grafana:
    extends:
      file: compose-observability.yml
      service: grafana

volumes:
  postgres-data:
  loki-data:
  grafana-data:
