version: "3.8"

services:
  web-app:
    build: .
    volumes:
      - "db:/app/db"
      - "${BACKUP_DIR}:/app/backup"
    hostname: grading-server
    ports:
      - "${PORT}:8080"
      - "127.0.0.1:9092:9092"
    environment:
      SERVER_SERVLET_CONTEXT_PATH: ${CONTEXT_PATH}
      JAVA_TOOL_OPTIONS: ${VM_ARGS}
      GRADING_SERVER_TEST_RUNNER_VM_ARGS: ${TEST_RUNNER_VM_ARGS}

volumes:
  db:
