version: "3.8"

services:
  web-app:
    build: web-app
    volumes:
      - "db:/app/db"
      - "${BACKUP_DIR}:/app/backup"
    hostname: grading-server
    ports:
      - "${PORT}:8080"
      - "127.0.0.1:9092:9092"
    environment:
      SERVER_SERVLET_CONTEXT_PATH: ${CONTEXT_PATH}

volumes:
  db:
