version: "3.8"

services:
  web-app:
    image: trick17/grading-server-web-app
    ports:
      - 8080:8080
    environment:
      GRADINGSERVER_WEBAPP_GRADINGSERVICEHOST: grading-service
  grading-service:
    image: trick17/grading-server-grading-service
