version: "3.8"

services:
  web-app:
    build:
      context: web-app
    volumes:
      - "web-app-db:/app/db"
      - "${BACKUP_DIR}:/app/backup"
    hostname: web-app
    ports:
      - "${WEBAPP_PORT}:8080"
      - "127.0.0.1:9092:9092"
    environment:
      SERVER_SERVLET_CONTEXT_PATH: ${WEBAPP_CONTEXT_PATH}

volumes:
  web-app-db:
