version: "3.8"

services:
  web-app:
    build:
      context: web-app
      dockerfile: "${DOCKERFILE}"
    volumes:
      - "web-app-db:/app/db"
      - "${BACKUP_DIR}:/app/backup"
    hostname: web-app
    ports:
      - "${WEBAPP_PORT}:8080"
      - "127.0.0.1:9092:9092"
    environment:
      SERVER_SERVLET_CONTEXT_PATH: ${WEBAPP_CONTEXT_PATH}
      GRADINGSERVER_WEBAPP_GRADINGSERVICEHOST: grading-service
  grading-service:
    build:
      context: grading-service
      dockerfile: ${DOCKERFILE}
    hostname: grading-service

volumes:
  web-app-db:
