INSERT INTO COURSE
    (ID, NAME, QUALIFIER, KIND, YEAR)
VALUES (1, 'OOPI1', '', 'FS', 24);

INSERT INTO PROBLEM_SET
(ID, DEADLINE, COMPILER, PERM_RESTRICTIONS, REP_TIMEOUT_MILLIS,
 REPETITIONS, TEST_TIMEOUT_MILLIS, PROJECT_ROOT, STRUCTURE,
 TEST_CLASS, NAME, REGISTERING_SOLUTIONS, COURSE_ID,
 PERCENTAGE_GOAL, DISPLAY_SETTING)
VALUES (2, '2024-03-01 23:59:00.000000', 0, false, 1000, 7, 5000,
        'aufgaben-01', 0, 'class FooTest {}', 'Foo', false, 1, 80, 1);

INSERT INTO PROBLEM_SET
(ID, DEADLINE, COMPILER, PERM_RESTRICTIONS, REP_TIMEOUT_MILLIS,
 REPETITIONS, TEST_TIMEOUT_MILLIS, PROJECT_ROOT, STRUCTURE,
 TEST_CLASS, NAME, REGISTERING_SOLUTIONS, COURSE_ID,
 PERCENTAGE_GOAL, DISPLAY_SETTING)
VALUES (3, '2024-03-01 23:59:00.000000', 1, true, 300, 5, 1500,
        'aufgaben-02', 1, 'class BarTest {}', 'Bar', false, 1, 80, 1);
