ALTER TABLE PROBLEM_SET
    ADD COLUMN DISPLAY_SETTING INT NOT NULL DEFAULT 1;

UPDATE PROBLEM_SET
SET DISPLAY_SETTING = 2
WHERE ANONYMOUS;

UPDATE PROBLEM_SET
SET DISPLAY_SETTING = 3
WHERE HIDDEN;

ALTER TABLE PROBLEM_SET
    DROP COLUMN ANONYMOUS, HIDDEN;

ALTER TABLE AUTHOR
    ALTER COLUMN NAME RENAME TO USERNAME;
